HEALTH_OPCODE = 0
MESSAGE_TO_ALL_OPCODE = 1
GIVE_ADMIN_OPCODE = 2
MUTE_USER_OPCODE = 4
UNMUTE_USER_OPCODE = 5
SERVER_ERROR_OPCODE = 7
REQUEST_ADMIN_OPCODE = 8


OPCODE = "opcode"
USER_NAME = "user_name"
CONTENT = "content"

MAX_MSG_LENGTH = 1024
